# Generated by Django 3.1.5 on 2021-11-01 10:58

import albums.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('name', models.CharField(max_length=350, null=True)),
                ('description', models.CharField(max_length=350, null=True)),
                ('private', models.BooleanField(default=True)),
                ('album_image', models.ImageField(blank=True, default='avatar.png', null=True, upload_to=albums.models.upload_album_location)),
                ('deleted', models.BooleanField(default=False)),
                ('favourite', models.BooleanField(default=False)),
                ('shared', models.BooleanField(default=False)),
                ('lock', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('blacklist', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('admins', models.ManyToManyField(null=True, related_name='admin', to='accounts.Account')),
                ('members', models.ManyToManyField(null=True, related_name='members', to='accounts.Account')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('filename', models.CharField(max_length=350, null=True)),
                ('file', models.FileField(max_length=22500, upload_to=albums.models.upload_location)),
                ('search_tag', models.CharField(max_length=350, null=True)),
                ('filetype', models.CharField(max_length=150, null=True)),
                ('fileSize', models.CharField(max_length=150, null=True)),
                ('fileExtension', models.CharField(max_length=150, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('favourite', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=150, null=True)),
                ('user_city', models.CharField(max_length=150, null=True)),
                ('user_country', models.CharField(max_length=150, null=True)),
                ('user_browser', models.CharField(max_length=150, null=True)),
                ('price', models.IntegerField(default=0)),
                ('lock', models.BooleanField(default=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('album', models.ManyToManyField(null=True, related_name='Albums', to='albums.Albums')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype', models.CharField(max_length=500, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.albums')),
                ('files', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.files')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='DeletedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype', models.CharField(max_length=500, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('permanent_delete', models.BooleanField(default=False)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.albums')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.files')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
