# Generated by Django 3.1.5 on 2021-12-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_waitlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, verbose_name='wait_email')),
                ('name', models.CharField(max_length=60, null=True)),
                ('message', models.CharField(max_length=6000, null=True)),
            ],
        ),
    ]
