# Generated by Django 3.1.5 on 2021-12-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
