# Generated by Django 3.1.5 on 2021-11-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('body', models.CharField(max_length=10000)),
                ('receiver', models.CharField(max_length=10000)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
